version: "3"
vars:
  DOCKER_IMAGE: ghcr.io/qmk/qmk_cli:latest
  KEYBOARD: "crkbd"
  REVISION: "rev4.1"
  MOUNT_POINT: "/Volumes/RPI-RP2" # Default for macOS; adjust for Linux
  KEYMAP: "default"
  VOYAGER_URL: https://oryx.zsa.io
  VOYAGER_LAYOUT_ID: ZPqal7
  VOYAGER_LAYOUT_NAME: default
  QMK_SOURCES: "~/qmk_firmware"
  QMK_USER_OVERLAY:
    sh: realpath .
tasks:
  setup:
    desc: "Pull the latest stable QMK sources."
    cmds:
      - |
        docker run -ti -v {{ .QMK_SOURCES }}:/qmk_firmware \
        -e http_proxy=http://host.docker.internal:3128 \
        -e https_proxy=http://host.docker.internal:3128 \
        --add-host=host.docker.internal:host-gateway \
        ghcr.io/qmk/qmk_cli:latest \
        /bin/sh -c "qmk setup -y"
    status:
      - test -d {{ .QMK_SOURCES }}

  download-voyager-sources:
    desc: "Download and extract Voyager keyboard sources to voyager directory."
    vars:
      TEMP_ZIP:
        sh: mktemp -u
      VOYAGER_SOURCES: "{{ .VOYAGER_URL }}/source/{{ .VOYAGER_LAYOUT_ID }}"
    cmds:
      - defer: rm -rf {{ .TEMP_ZIP }}.zip
      - curl {{ .VOYAGER_SOURCES }} -o {{ .TEMP_ZIP }}.zip
      - unzip -o {{ .TEMP_ZIP }}.zip "zsa_voyager_{{ .VOYAGER_LAYOUT_NAME }}_source/*"
      - mv zsa_voyager_{{ .VOYAGER_LAYOUT_NAME }}_source voyager

  .setup-userspace-config:
    cmds:
      - qmk config user.overlay_dir="{{ .QMK_USER_OVERLAY }}"
    status:
      - test "$(qmk config user.overlay_dir)" = "user.overlay_dir={{ .QMK_USER_OVERLAY }}"

  build:
    desc: "Build the firmware and generate a .uf2 file for the specified keyboard/revision and keymap."
    cmds:
      - |
        docker run -ti \
        -v {{ .QMK_SOURCES }}:/qmk_firmware \
        -v .:/qmk_userspace \
        -w /qmk_userspace \
        ghcr.io/qmk/qmk_cli:latest \
        /bin/sh -c "qmk compile -kb crkbd/rev4_1/standard -km zbindenren"

  clean-qmk-source:
    cmds:
      - rm -rf {{ .QMK_SOURCES }}

  clean-build:
    cmds:
      - rm -rf *.uf2

  clean-voyager:
    cmds:
      - rm -rf voyager
      - rm -rf zsa_voyager*

  clean-repo:
    desc: Cleanup
    deps:
      - clean-voyager
      - clean-build
